# Generated by Django 2.2.7 on 2019-11-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paco',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='paco',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='paco',
            name='like_donuts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paco',
            name='waste_time',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paco',
            name='has_a_gun',
            field=models.BooleanField(default=True),
        ),
    ]
